# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cadena', models.IntegerField(blank=True, null=True)),
                ('cadena', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_precio', models.IntegerField(blank=True, null=True)),
                ('fecha_hora', models.TextField(blank=True, null=True)),
                ('id_producto', models.IntegerField(blank=True, null=True)),
                ('id_cadena', models.IntegerField(blank=True, null=True)),
                ('precio_c_descuento', models.TextField(blank=True, null=True)),
                ('precio', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.IntegerField(blank=True, null=True)),
                ('producto', models.CharField(blank=True, max_length=255, null=True)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad', models.CharField(blank=True, max_length=2, null=True)),
                ('cantidad', models.TextField(blank=True, null=True)),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
