# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_precios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_precios.Producto'),
        ),
    ]
