# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_precios', '0006_auto_20180928_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='precio',
            name='id_cadena',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_precios.Cadena'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='precio',
            name='precio_c_descuento',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('LT', 'LT'), ('GR', 'GR'), ('KL', 'KL')], default='lt', max_length=2),
        ),
    ]
